### ISSUE TITLE
`gx` isn't working with Vim 9.1

### ISSUE THREAD

**Issue by rbohl** [preservim/vim-markdown#671]
Using `gx` on a link in a markdown file doesn't work, with the error:
```
Error detected while processing function <SNR>37_OpenUrlUnderCursor[8]..<SNR>37_VersionAwareNetrwBrowseX:
E118: Too many arguments for function: netrw#BrowseX
```

Vim version 9.1:
```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Aug 10 2025 19:46:14)
Included patches: 1-1623
Compiled by Arch Linux
Huge version without GUI.
```

I believe it's a vim-markdown issue because after blacklisting the plugin, Vim's default `gx` works as expected.

**Comment by talex5** [comment]
The plugin passes two arguments to `BrowseX`:

https://github.com/preservim/vim-markdown/blob/8f6cb3a6ca4e3b6bcda0730145a0b700f3481b51/ftplugin/markdown.vim#L746-L752

But https://github.com/vim/vim/pull/17616 changed it to accept only one. See https://github.com/vim/vim/issues/17794 - it looks like `:Open` should be used now instead.

**Comment by alerque** [comment]
Thanks for tracking down a fix @talex5. Can you PR that change please? I suppose we'll need another conditional checking for the VIM version that introduced that change, then fall back to the current two backup options.

**Comment by alerque** [comment]
Can anybody check and confirm that #674 works for them, either the old usage still working on older VIM and/or the new usage working on fresh VIM versions?

Note that this has *not* landed in Neovim yet so Neovim users should still get the old usage, but I haven't confirm that as working either.

**Comment by rbohl** [comment]
Hey, it works on my 9.1. Thank you!

**Comment by alerque** [comment]
I just confirmed that this does *not* work in VIM 9.1.1841, so something is wrong. Perhaps this changed merged earlier than what I found...
